### ISSUE TITLE
LESS语法

### ISSUE THREAD

**Issue by yingwinwin** [yingwinwin/yingwinwin.github.io#9]
[LESS课程](https://www.bilibili.com/video/av74364759?p=4)笔记

### 变量
- 普通变量
```less
@color : #fff
.header{
    background : @color
    div{
      color : #f83
    }
}
```
- 选择器和属性名的变量
```html
<div class = "width">
    <h1>123<h1>
</div>
```
```less
@kuandu: width
// 选择器的名字需要与属性名一致
@{kuandu}:{
    @kuandu: 150px;
}
```

- url变量
```less
@imgurl : 'https://www.baidu.com/img/'
.header{
  img:url('@{imgurl}bdlogo.png')
}
```
- less变量有声明提升
- 有作用域的概念，重复命名，会选择离它最近的属性值

**Comment by yingwinwin** [comment]
### 混合
- 普通混合
```less
.font_hn{
color:#f38;
font-size:'黑体'
}
.h1{
font-size:28px;
.font_hn
}
.h2{
font-size:24px;
.font_hn
}
```

- 不带输出的混合
```less
//在这里加一个()，就可以不输出，其他和普通没区别
.font_hn(){
color:#f38;
font-size:'黑体'
}
.h1{
//两个字体只有大小不同。其他属性都相同。
font-size:28px;
.font_hn
}
.h2{
font-size:24px;
.font_hn
}
```

- 带选择器的混合
```less
.my_hover{
 &:hover{
   boder: 1px solid #000;
  }
}
button{
//给鼠标浮动给按钮加边框
  .my_hover();
}
```

- 带混合的参数
```
.border(@color){
   border: 1px solid @color;
}
h1{
//给border函数传参。h1边框是绿色。h2是黑色
 &:hover{
  .border(green);
 }
}
h2{
 &:hover{
  .border(#000);
 }
}
```

- 带默认参数的混合
```
//border这里要参数有一个默认值，不传参也可以，默认是红色，传参就会覆盖
.border(@color:red){
   border: 1px solid @color;
}
h1{
 &:hover{
//默认红色
  .border();
 }
}
h2{
 &:hover{
//覆盖红色为黑色
  .border(#000);
 }
}
```

- 带有多个参数的混入
```less
.mixin(@color:red,@margin, @bcolor){
  color:@color;
  margin: @margin @maring @margin @margin;
  border : 1px solid @bcolor
}

h1{
//如果要穿几个参数的话，用分号分隔会让解析器理解为分号前面是一个参数。
//逗号分隔是为一个参数的几个值，但是如果传参的时候只有逗号，那么就理解为不同的三个参数。
 .mixin(#fff ; 3 ; #eee)
}
```

- 命名参数
```less
.mixin(@color:red,@margin:2, @bcolor){
  color:@color;
  margin: @margin @maring @margin @margin;
  border : 1px solid @bcolor
}
h1{
//如果不命名就是默认从左向右传参，如果命名了，就直接匹配参数名称，跳过中间的参数
 .mixin(yellow ; @bcolor:red)
}
```

-arguments模式
```less
.border(@x:solid, @c:#000){
//默认显示其他所有参数
  border: 21px @arguments;
}
h1{
  .border()
}
```
- 匹配模式
```less
.border(all,@w:5px){
  border-radius:@w;
}
.border(b_tl){
 border-top-left-radius:@w;
}
footer{
//根据第一个参数，匹配不一样的混入规则
  .border(all, 10px)
  .border(b_tl, 20px)
}
```

- 混入的返回值
```less
.average(@x, @y){
  @average:((@x + @y) / 2)
}
div{
//先调用传值，然后再用里面的变量。
 .average(15px , 20px)
 padding:@average;
}
```

**Comment by yingwinwin** [comment]
### 嵌套规则
- 普通嵌套
```less
.header{
    background-color: #fff;
    div{
        color: #f38;
    }
}
```
```css
.header {
  background-color: #fff;
}
.header div {
  color: #f38;
}
```
- &嵌套
```less
.header{
    background-color: #fff;
    &:hover div{
        color: #f38;
    }
}
```
```css
.header {
  background-color: #fff;
}
.header:hover div {
  color: #f38;
}
```
- 反向嵌套
```less
.header{
    background-color: #fff;
    &:hover &{
        color: #f38;
    }
}
```
```css
.header {
  background-color: #fff;
}
.header:hover .header {
  color: #f38;
}
```
- 列出所有组合嵌套
```less
ul, li, p{
    background-color: #fff;
    & &{
        color: #f38;
    }
}
```
```css
ul,
li,
p {
  background-color: #fff;
}
ul ul,
ul li,
ul p,
li ul,
li li,
li p,
p ul,
p li,
p p {
  color: #f38;
}
```

**Comment by yingwinwin** [comment]
### 计算
- 普通计算
```less
//可以进行加减乘除运算,写一个单位就可以
.wp{
  background: #000;
  width: 450px + 450;
  height: 400px + 400;
}
```
```css
.wp {
  background: #000;
  width: 900px;
  height: 800px;
}
```
- RGB运算
```less
//转换为rgb格式之后,给r+21.g+21,b+21
.wp{
  background: #000 + 21;
  width: (450px + 450)*2;
  height: 400px + 400;
}
```
```css
/* 得到 #151515 */
.wp {
  background: #151515;
  width: 1800px;
  height: 800px;
}
```

**Comment by yingwinwin** [comment]
### 函数
- RGB 函数
```less
//把rgb转为16进制颜色
.wp{
  background: rgb(255,0,0);
}
```
```css
.wp {
  background: #ff0000;
}
```

### 命名空间
```less
#bgcolor(){
  background: #fff;
  .a{
    color: #888;
    &:hover{
      color:#ff6600;
    }
    .b{
      background: #ff0;
    }
  }
}

.bgcolor1{
  background: #fdfee0;
  #bgcolor>.a
}

.bgcolor2{
  #bgcolor>.a>.b
//#bgcolor .a .b  可把>换为空格
}
```
```css
.bgcolor1 {
  background: #fdfee0;
  color: #888;
}
.bgcolor1:hover {
  color: #ff6600;
}
.bgcolor1 .b {
  background: #ff0;
}
.bgcolor2 {
  background: #ff0;
}
```

### 作用域
```less
@color:#fff; //接着选择它

.bgcolor{
  width: 50px;
  .a{
    @color:green;  //优选选择它
    color: @color;
  }
  @color:#ff0000;  //然后选择它
}
```
```css
.bgcolor {
  width: 50px;
}
.bgcolor .a {
  color: green;
}
```

### 引入
@import 'main';  普通引入
@import (reference) 'main';  按需输出
@import (inline) 'main.less';  输出但是不加工
@import (once) 'main.less';   默认,只能引入一次
@import (css) 'main.less';   如论引入什么文件都以css文件加工
@import (less) 'main.less';   如论引入什么文件都以less文件加工
@import (multiple) 'main.less';   允许同文件名文件引入多次

### 关键字
```less
.foo(@bg:#f5f5f5,@color:#900){
  background: @bg;
  color: @color;
  font-size: 16px;
}

.unimportant{
  .foo();
}
.unimportant{
  .foo()!important;
}
```
```css
.unimportant {
  background: #f5f5f5;
  color: #900;
  font-size: 16px;
}
.unimportant {
  background: #f5f5f5 !important;
  color: #900 !important;
  font-size: 16px !important;
}
```

### 条件表达式
```less
.mixin(@a) when (lightness(@a) >= 50%){  //127.5
  background-color: #000;
}
.mixin(@a) when (lightness(@a) < 50%){   //128
  background-color: #fff;
}
.mixin(@a){
  color: @a;
}

.class1{
  .mixin(#ddd);
}
.class2{
  .mixin(#555)
}
```
```css
.class1 {
  background-color: #000;
  color: #ddd;
}
.class2 {
  background-color: #fff;
  color: #555;
}
```
- 数据类型检查
1. iscolor()  检查是否为颜色值
2. isnumber() 检查是否为数字
3. isstring() 检查是否是字符串
4. iskeyword() 检查是否是关键字
5. isurl()   检查是否是url

- 单位类型检查
1. ispixel() 检查是否是像素
2. ispercentage() 检查是否是百分比
3. isem() 检查是否是em
4. isunit() 检查是否是unit

### 循环
```less
.loop(@counter) when (@counter > 0){
  h@{counter}{
    padding:(10px * @counter);
  }
  .loop(@counter - 1);  //递归
}

div{
  .loop(6);
}
```
```css
div h6 {
  padding: 60px;
}
div h5 {
  padding: 50px;
}
div h4 {
  padding: 40px;
}
div h3 {
  padding: 30px;
}
div h2 {
  padding: 20px;
}
div h1 {
  padding: 10px;
}
```
### 合并属性
- +合并以后以逗号分隔
```less
.mixin(){
  box-shadow+: inset 0 0 10px #555;
}
.myclass{
  .mixin();
  box-shadow+: 0 0 20px #000;
}
```
```css
.myclass {
  box-shadow: inset 0 0 10px #555, 0 0 20px #000;
}
```

- +_合并以后以空格分隔
```less
.a(){
  background+_: #000;
  background+_: url(../ansel/d);
}
.maclass{
  .a()
}
```
```css
.maclass {
  background: #000 url(../ansel/d);
}
```
